//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FR.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FR.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Enroll.
        /// </summary>
        internal static string AddEnroll {
            get {
                return ResourceManager.GetString("AddEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and .
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Card Number.
        /// </summary>
        internal static string BankCardNumber {
            get {
                return ResourceManager.GetString("BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Info.
        /// </summary>
        internal static string BankInfo {
            get {
                return ResourceManager.GetString("BankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up, you agree to the .
        /// </summary>
        internal static string BySignUpAndYouAgree {
            get {
                return ResourceManager.GetString("BySignUpAndYouAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Image.
        /// </summary>
        internal static string ChangeProfileImage {
            get {
                return ResourceManager.GetString("ChangeProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatting Room.
        /// </summary>
        internal static string ChattingRoom {
            get {
                return ResourceManager.GetString("ChattingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common chat room for all users.
        /// </summary>
        internal static string ChattingRoomDescription {
            get {
                return ResourceManager.GetString("ChattingRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHATTING ROOM.
        /// </summary>
        internal static string ChattingRoomUC {
            get {
                return ResourceManager.GetString("ChattingRoomUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click And Enter.
        /// </summary>
        internal static string ClickAndEnter {
            get {
                return ResourceManager.GetString("ClickAndEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? .
        /// </summary>
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        internal static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Please fill according to your personal requirement carefully.
        /// </summary>
        internal static string EnrollRule1 {
            get {
                return ResourceManager.GetString("EnrollRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. When the pre-sale amount reach 450, 000, will activate the first split 300, 000 sale.
        /// </summary>
        internal static string EnrollRule2 {
            get {
                return ResourceManager.GetString("EnrollRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. According to the subscription queue ordering execute payment transaction and position..
        /// </summary>
        internal static string EnrollRule3 {
            get {
                return ResourceManager.GetString("EnrollRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Unable to make the payment transaction, the position will auto fall..
        /// </summary>
        internal static string EnrollRule4 {
            get {
                return ResourceManager.GetString("EnrollRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. During the valid period notice of payment, pre-order person unable to make the payment, and after confirm by both parties, he or she will forfeit..
        /// </summary>
        internal static string EnrollRule5 {
            get {
                return ResourceManager.GetString("EnrollRule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. For multiple accounts, please upload a diagram showing how to place. Leave your name / phone number / username / position. First comer will location in higher position.
        /// </summary>
        internal static string EnrollRule6 {
            get {
                return ResourceManager.GetString("EnrollRule6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: Pre-sale plan can enjoy preferential treatment (one ID card, can only invest 3 package), Due date is January 31, 2017. Only open from one star to four star package, bonus treatment is 1 star to enjoy 3 stars, 2 stars to enjoy 4 stars, 3 stars to enjoy 5 stars, 4 stars to enjoy 6 stars for 1 month.
        /// </summary>
        internal static string EnrollRule7 {
            get {
                return ResourceManager.GetString("EnrollRule7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like Delete.
        /// </summary>
        internal static string FavDeleteConfirmation {
            get {
                return ResourceManager.GetString("FavDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favourite.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR Chat.
        /// </summary>
        internal static string FRChat {
            get {
                return ResourceManager.GetString("FRChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All info about FR member.
        /// </summary>
        internal static string FRChatDescription {
            get {
                return ResourceManager.GetString("FRChatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get back your password, please contact our customer service..
        /// </summary>
        internal static string GetBackPasswordInfo {
            get {
                return ResourceManager.GetString("GetBackPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorrect.
        /// </summary>
        internal static string IncorrectCredential {
            get {
                return ResourceManager.GetString("IncorrectCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        internal static string MenuFavourite {
            get {
                return ResourceManager.GetString("MenuFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message already copy to clipboard.
        /// </summary>
        internal static string MessageAlreadyCopy {
            get {
                return ResourceManager.GetString("MessageAlreadyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added To Favourite.
        /// </summary>
        internal static string MessageFavAdded {
            get {
                return ResourceManager.GetString("MessageFavAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Deleted Successfully.
        /// </summary>
        internal static string MessageFavDeleted {
            get {
                return ResourceManager.GetString("MessageFavDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Friends.
        /// </summary>
        internal static string MyFriends {
            get {
                return ResourceManager.GetString("MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY FRIENDS.
        /// </summary>
        internal static string MyFriendsUC {
            get {
                return ResourceManager.GetString("MyFriendsUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROFILE.
        /// </summary>
        internal static string MyProfileUC {
            get {
                return ResourceManager.GetString("MyProfileUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Friend Request List.
        /// </summary>
        internal static string NewFriendRequestList {
            get {
                return ResourceManager.GetString("NewFriendRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera.
        /// </summary>
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available..
        /// </summary>
        internal static string NoCameraAvailable {
            get {
                return ResourceManager.GetString("NoCameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input telephone number.
        /// </summary>
        internal static string NoTelephoneNumber {
            get {
                return ResourceManager.GetString("NoTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. buy milk.
        /// </summary>
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input user name.
        /// </summary>
        internal static string NoUserName {
            get {
                return ResourceManager.GetString("NoUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password incorrect.
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not granted to photos..
        /// </summary>
        internal static string PermissionNotGrantedToPhotos {
            get {
                return ResourceManager.GetString("PermissionNotGrantedToPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Not Supported.
        /// </summary>
        internal static string PhotosNotSupported {
            get {
                return ResourceManager.GetString("PhotosNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a number.
        /// </summary>
        internal static string PickerName {
            get {
                return ResourceManager.GetString("PickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check the internat connection.
        /// </summary>
        internal static string PleaseCheckInternatConnection {
            get {
                return ResourceManager.GetString("PleaseCheckInternatConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Sale Group.
        /// </summary>
        internal static string PreSaleGroup {
            get {
                return ResourceManager.GetString("PreSaleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Sale Plan, Preconceptions!.
        /// </summary>
        internal static string PreSaleGroupDescription {
            get {
                return ResourceManager.GetString("PreSaleGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Policy.
        /// </summary>
        internal static string PrivatePolicy {
            get {
                return ResourceManager.GetString("PrivatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        internal static string SearchUser {
            get {
                return ResourceManager.GetString("SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Friend Request.
        /// </summary>
        internal static string SendFriendRequest {
            get {
                return ResourceManager.GetString("SendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send PM To.
        /// </summary>
        internal static string SendPMTo {
            get {
                return ResourceManager.GetString("SendPMTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of Service.
        /// </summary>
        internal static string TermOfService {
            get {
                return ResourceManager.GetString("TermOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username And Password Required.
        /// </summary>
        internal static string UsernameAndPasswordRequired {
            get {
                return ResourceManager.GetString("UsernameAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message....
        /// </summary>
        internal static string WriteAMessage {
            get {
                return ResourceManager.GetString("WriteAMessage", resourceCulture);
            }
        }
    }
}
